/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC20LP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20LP__factory>;
    getContractFactory(
      name: "IlpDeployer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IlpDeployer__factory>;
    getContractFactory(
      name: "LPDeployer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LPDeployer__factory>;
    getContractFactory(
      name: "LPFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LPFactory__factory>;
    getContractFactory(
      name: "LPFarm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LPFarm__factory>;
    getContractFactory(
      name: "RewardToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RewardToken__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC20LP",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20LP>;
    getContractAt(
      name: "IlpDeployer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IlpDeployer>;
    getContractAt(
      name: "LPDeployer",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LPDeployer>;
    getContractAt(
      name: "LPFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LPFactory>;
    getContractAt(
      name: "LPFarm",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LPFarm>;
    getContractAt(
      name: "RewardToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RewardToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
